Update CODEOWNERS
camaraproject/NumberRecycling pull request #4
Opened 2024-09-23 16:57 UTC by jgarciahospital

#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Including initial list of maintainer/codeowner

#### Which issue(s) this PR fixes:

2024-09-23 17:20 UTC, hdamker requested changes
Sent invitations to @Masa810 and @yamamoto0104 to get members of the CAMARA organization. Waiting for the acceptance of the invitations.

2024-09-24 07:58 UTC, Masa8106 commented
@jgarciahospital , @hdamker  I have accepted the invitation. Thank you.

2024-09-24 08:38 UTC, yamamoto0104 commented
@jgarciahospital , @hdamker , Thank you for updating CODEOWNERS and MAINTAINERS.md.
I also accepted the invitation.

2024-09-25 05:31 UTC, ToshiWakayama-KDDI commented
Thanks very much, @jgarciahospital and @hdamker, for processing with this.  

To @Herbert, could you provide Codeowners/Maintaienrs from DT, please, so that we could start working on this API.

Many thanks,
Toshi
KDDI

2024-10-01 08:32 UTC, ToshiWakayama-KDDI commented
Hi @jgarciahospital , @hdamker ,

We have just had a KYC SP meeting today, and confirmed that @grgpapadopoulos (Georgios Papadopoulos) is the codeowner from DT.  So, @jgarciahospital , could you add Georgios to the Codeowner file in this PR?  

Then, @hdamker , could you approve and merge the codeowner update?  Or, do you need to merge this PR including both of codeowner and maintainer updates altogether? 

For Maintainers, we are waiting for DT's response, which is expected by the end of today.

Many thanks,
Toshi
KDDI

2024-10-01 08:40 UTC, hdamker commented on CODEOWNERS
> +* @eric-murray @Masa8106
```suggestion
* @eric-murray @Masa8106 @grgpapadopoulos
```

2024-10-01 08:42 UTC, hdamker commented on MAINTAINERS.MD
> +| KDDI | Kenichi Yamamoto | @yamamoto0104  |
```suggestion
| KDDI | Kenichi Yamamoto | @yamamoto0104  |
| DT | Georgios Papadopoulos | grgpapadopoulos |
| DT | Noel Wirzius | NoelWirzius |
```

2024-10-01 08:43 UTC, jgarciahospital commented
Solved. If @ToshiWakayama-KDDI you feel confortable with current proposal, I think @hdamker that we can merge.

2024-10-01 08:46 UTC, jgarciahospital commented
Ready. @ToshiWakayama-KDDI please confirm to that @hdamker can merge.

2024-10-01 08:47 UTC, hdamker approved these changes

2024-10-01 08:50 UTC, hdamker commented
> Ready. @ToshiWakayama-KDDI please confirm to that @hdamker can merge.

Thanks @jgarciahospital @ToshiWakayama-KDDI. I've added @grgpapadopoulos and @NoelWirzius to Maintainers.md, so that it is currently on par with the Tenure repository regarding DT. If there are changes they can be done in a new PR.

Here we are done. I'll take https://github.com/camaraproject/NumberRecycling/pull/4#issuecomment-2385130416 as approval from @ToshiWakayama-KDDI (technically I don't need it).

2024-10-01 08:50 UTC, merged